let str = "My Name is Gaurav Verma  ";
// let str1 = "I am B.tech Student";
// let length = str.length;
// console.log(length);
// let concat = str.concat(str1);
// console.log(concat);
// let char = str.charAt(3);
// console.log(char);
// let uppercase = str.toUpperCase();
// console.log(uppercase);
// let lowercase = str.toLowerCase();
// console.log(lowercase);
// let trim = str.trim();
// console.log(trim);
// let slice = str.slice(3, 8);
// console.log(slice);
// let replace = str.replace("Gaurav", "gourav");
// console.log(replace);
// let replaceall = str.replaceAll(/gaurav/gi, "GAURAV");
// console.log(replaceall);
// let includes = str.includes("Gaurav");
// console.log(includes);
// let match = str.match("rav");
// console.log(match);
let splitted = str.split(" ");
console.log(splitted);
